version: '3.8'
services:
  frontend:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=UFA-prod
    ports:
      - '3001:80'