version: '3.8'
services:
  frontend:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./:/ufaApp
    environment:
      - REACT_APP_NAME= UFA-dev
      - CHOKIDAR_USEPOLLING= true