FROM node:14.17.3-alpine3.14 as build
WORKDIR /ufaApp
COPY package.json .
RUN npm install -g npm@8.5.4
RUN npm install --save --legacy-peer-deps
COPY . .
ARG REACT_APP_NAME
ENV REACT_APP_NAME = ${REACT_APP_NAME}
RUN npm run build

FROM nginx
COPY --from=build /ufaApp/build /usr/share/nginx/html

