version: '3.8'
services:
  frontend:
    # stdin_open: true
    # tty: true
    build:
      context: .
      dockerfile: Dockerfile.prod
    # build:
    #   context: .
    #   dockerfile: Dockerfile.dev

